### ISSUE TITLE
Initial CI Setup

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/sirius#2]
## Stage 1
- [x] [link slack](https://github.com/apps/slack/installations/2771236)
- [x] [add semantic pr](https://github.com/apps/semantic-pull-requests) to check commit message and pr title, configuration added in #1  
- [x] [add vercel](https://vercel.com/import) to have a viewable site each commit, have at least one PR to test the functionality of vercel preview

## Stage 2
- [x] add at least one unit test
- [x] [add circleci](https://app.circleci.com/projects/project-dashboard/github/Conflux-Chain/) to run lint and unit test   
- [x] add both the [codecov](https://github.com/marketplace/codecov) github app and [codecov oauth app](https://codecov.io/gh) into this repo (maybe later) 
## Stage 3
- [ ] add at least e2e test using [cypress](https://github.com/cypress-io/cypress#readme) 
- [ ] run e2e test within CI
